# mpc
receding: 3
step_time: 0.2
ref_speed: 1.9
device: 'cpu'
time_print: False
collision_threshold: 0.05

# robot
robot:
  kinematics: 'diff'
  max_speed: [1.5, 4.0]
  max_acce: [1.5, 4.0]
  length: 0.75
  width: 0.50

# initial path
ipath:
  interval: 0.1
  waypoints: [[0, 0, 0], [8, 0, 0], [8, 8, 0], [0, 8, 0], [0, 0, 0]]
  curve_style: 'line'   # 'dubins' or reeds or line
  min_radius: 0.0
  loop: True
  arrive_threshold: 0.2
  close_threshold: 0.05
  arrive_index_threshold: 1
  
# proximal alternating minimization network
pan:
  iter_num: 2
  dune_max_num: 100
  nrmp_max_num: 10
  dune_checkpoint: None
  iter_threshold: 0.1

# adjust parameters
adjust:
  q_s: 0.1
  p_u: 2.5
  eta: 30.0
  d_max: 0.3
  d_min: 0.01
